// GENERATED by scripts/gen-data.mjs from data/. Do not edit; run `pnpm gen`.
export interface DataBundle {
  gpus: any[]
  assumptions: Record<string, any>
  quant: any
  archDefaults: Record<string, any>
  models: Record<string, any>
  validation: any[]
}

export const DATA: DataBundle = {
 "gpus": [
  {
   "id": "h100-sxm-80",
   "name": "NVIDIA H100 SXM5 80GB",
   "vendor": "nvidia",
   "vramBytes": 85899345920,
   "memoryType": "HBM3",
   "memBandwidthBytesPerSec": 3352000000000,
   "tflopsDense": {
    "fp32": 67,
    "tf32": 494.7,
    "fp16": 989.4,
    "bf16": 989.4,
    "fp8": 1978.9,
    "int8": 1978.9
   },
   "interconnect": {
    "kind": "nvlink4",
    "bidirectionalBytesPerSec": 900000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://resources.nvidia.com/en-us-tensor-core/nvidia-tensor-core-gpu-datasheet"
  },
  {
   "id": "h100-pcie-80",
   "name": "NVIDIA H100 PCIe 80GB",
   "vendor": "nvidia",
   "vramBytes": 85899345920,
   "memoryType": "HBM2e",
   "memBandwidthBytesPerSec": 2000000000000,
   "tflopsDense": {
    "fp32": 51,
    "tf32": 378,
    "fp16": 756.5,
    "bf16": 756.5,
    "fp8": 1513,
    "int8": 1513
   },
   "interconnect": {
    "kind": "nvlink-bridge",
    "bidirectionalBytesPerSec": 600000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://resources.nvidia.com/en-us-tensor-core/nvidia-tensor-core-gpu-datasheet"
  },
  {
   "id": "h200-sxm-141",
   "name": "NVIDIA H200 SXM 141GB",
   "vendor": "nvidia",
   "vramBytes": 151397597184,
   "memoryType": "HBM3e",
   "memBandwidthBytesPerSec": 4800000000000,
   "tflopsDense": {
    "fp32": 67,
    "tf32": 494.7,
    "fp16": 989.4,
    "bf16": 989.4,
    "fp8": 1978.9,
    "int8": 1978.9
   },
   "interconnect": {
    "kind": "nvlink4",
    "bidirectionalBytesPerSec": 900000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://resources.nvidia.com/en-us-data-center-overview/hpc-datasheet-sc23-h200"
  },
  {
   "id": "b200-sxm-192",
   "name": "NVIDIA B200 SXM 192GB",
   "vendor": "nvidia",
   "vramBytes": 206158430208,
   "memoryType": "HBM3e",
   "memBandwidthBytesPerSec": 8000000000000,
   "tflopsDense": {
    "fp32": 80,
    "tf32": 1100,
    "fp16": 2250,
    "bf16": 2250,
    "fp8": 4500,
    "int8": 4500,
    "fp4": 9000
   },
   "interconnect": {
    "kind": "nvlink5",
    "bidirectionalBytesPerSec": 1800000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://resources.nvidia.com/en-us-blackwell-architecture/datasheet"
  },
  {
   "id": "a100-sxm-80",
   "name": "NVIDIA A100 SXM4 80GB",
   "vendor": "nvidia",
   "vramBytes": 85899345920,
   "memoryType": "HBM2e",
   "memBandwidthBytesPerSec": 2039000000000,
   "tflopsDense": {
    "fp32": 19.5,
    "tf32": 156,
    "fp16": 312,
    "bf16": 312,
    "int8": 624
   },
   "interconnect": {
    "kind": "nvlink3",
    "bidirectionalBytesPerSec": 600000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/pdf/nvidia-a100-datasheet-us-nvidia-1758950-r4-web.pdf"
  },
  {
   "id": "a100-pcie-80",
   "name": "NVIDIA A100 PCIe 80GB",
   "vendor": "nvidia",
   "vramBytes": 85899345920,
   "memoryType": "HBM2e",
   "memBandwidthBytesPerSec": 1935000000000,
   "tflopsDense": {
    "fp32": 19.5,
    "tf32": 156,
    "fp16": 312,
    "bf16": 312,
    "int8": 624
   },
   "interconnect": {
    "kind": "nvlink-bridge",
    "bidirectionalBytesPerSec": 600000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/pdf/nvidia-a100-datasheet-us-nvidia-1758950-r4-web.pdf"
  },
  {
   "id": "a100-sxm-40",
   "name": "NVIDIA A100 SXM4 40GB",
   "vendor": "nvidia",
   "vramBytes": 42949672960,
   "memoryType": "HBM2",
   "memBandwidthBytesPerSec": 1555000000000,
   "tflopsDense": {
    "fp32": 19.5,
    "tf32": 156,
    "fp16": 312,
    "bf16": 312,
    "int8": 624
   },
   "interconnect": {
    "kind": "nvlink3",
    "bidirectionalBytesPerSec": 600000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/a100/pdf/nvidia-a100-datasheet-us-nvidia-1758950-r4-web.pdf"
  },
  {
   "id": "l40s-48",
   "name": "NVIDIA L40S 48GB",
   "vendor": "nvidia",
   "vramBytes": 51539607552,
   "memoryType": "GDDR6",
   "memBandwidthBytesPerSec": 864000000000,
   "tflopsDense": {
    "fp32": 91.6,
    "tf32": 183,
    "fp16": 362.05,
    "bf16": 362.05,
    "fp8": 733,
    "int8": 733
   },
   "interconnect": {
    "kind": "pcie5",
    "bidirectionalBytesPerSec": 64000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://resources.nvidia.com/en-us-l40s/l40s-datasheet-28413"
  },
  {
   "id": "l4-24",
   "name": "NVIDIA L4 24GB",
   "vendor": "nvidia",
   "vramBytes": 25769803776,
   "memoryType": "GDDR6",
   "memBandwidthBytesPerSec": 300000000000,
   "tflopsDense": {
    "fp32": 30.3,
    "tf32": 60,
    "fp16": 121,
    "bf16": 121,
    "fp8": 242,
    "int8": 242
   },
   "interconnect": {
    "kind": "pcie4",
    "bidirectionalBytesPerSec": 32000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://resources.nvidia.com/en-us-l4/l4-datasheet"
  },
  {
   "id": "a10g-24",
   "name": "NVIDIA A10G 24GB",
   "vendor": "nvidia",
   "vramBytes": 25769803776,
   "memoryType": "GDDR6",
   "memBandwidthBytesPerSec": 600000000000,
   "tflopsDense": {
    "fp32": 31.5,
    "tf32": 62.5,
    "fp16": 125,
    "bf16": 125,
    "int8": 250
   },
   "interconnect": {
    "kind": "pcie4",
    "bidirectionalBytesPerSec": 32000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://d1.awsstatic.com/product-marketing/ec2/NVIDIA_AWS_A10G_DataSheet_FINAL_02_17_2022.pdf"
  },
  {
   "id": "rtx4090-24",
   "name": "NVIDIA GeForce RTX 4090 24GB",
   "vendor": "nvidia",
   "vramBytes": 25769803776,
   "memoryType": "GDDR6X",
   "memBandwidthBytesPerSec": 1008000000000,
   "tflopsDense": {
    "fp32": 82.6,
    "tf32": 82.6,
    "fp16": 165.2,
    "bf16": 165.2,
    "fp8": 660.6,
    "int8": 660.6
   },
   "interconnect": {
    "kind": "pcie4",
    "bidirectionalBytesPerSec": 32000000000
   },
   "sparsity_excluded": true,
   "notes": "fp16/bf16 figure is with FP32 accumulate, which is what inference kernels use. FP16-accumulate peaks at 330.3 dense but is not the serving path.",
   "source_url": "https://images.nvidia.com/aem-dam/Solutions/geforce/ada/nvidia-ada-gpu-architecture.pdf"
  },
  {
   "id": "mi300x-192",
   "name": "AMD Instinct MI300X 192GB",
   "vendor": "amd",
   "vramBytes": 206158430208,
   "memoryType": "HBM3",
   "memBandwidthBytesPerSec": 5300000000000,
   "tflopsDense": {
    "fp32": 163.4,
    "tf32": 653.7,
    "fp16": 1307.4,
    "bf16": 1307.4,
    "fp8": 2614.9,
    "int8": 2614.9
   },
   "interconnect": {
    "kind": "infinity-fabric",
    "bidirectionalBytesPerSec": 896000000000
   },
   "sparsity_excluded": true,
   "source_url": "https://www.amd.com/content/dam/amd/en/documents/instinct-tech-docs/data-sheets/amd-instinct-mi300x-data-sheet.pdf"
  }
 ],
 "assumptions": {
  "driver_reserved_vram_fraction": {
   "value": 0.004,
   "unit": "fraction",
   "rationale": "nvidia-smi reports slightly less total memory than the nominal capacity (ECC/driver/page tables). e.g. an 80GB H100 reports ~81559 MiB of 81920 MiB nominal (0.44%).",
   "source_url": "https://forums.developer.nvidia.com/t/why-does-nvidia-smi-report-less-memory-than-the-gpu-has/64165",
   "confidence": "medium"
  },
  "cuda_context_bytes": {
   "value": 536870912,
   "unit": "bytes",
   "rationale": "CUDA context + cuBLAS/cuDNN workspaces + NVML per process, before any model load. vLLM reports this as part of 'non-torch memory'; commonly 0.3-0.9 GiB depending on driver and CUDA version.",
   "source_url": "https://github.com/vllm-project/vllm/blob/main/vllm/worker/worker.py",
   "confidence": "low"
  },
  "nccl_buffer_bytes_per_rank": {
   "value": 536870912,
   "unit": "bytes",
   "rationale": "NCCL communicator buffers + CUDA IPC handles per rank when TP>1. Driven by NCCL_BUFFSIZE (default 4MiB per channel) times channels, plus graph-captured comm buffers. 0.5 GiB is the commonly observed delta between TP=1 and TP=2 non-torch memory.",
   "source_url": "https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html",
   "confidence": "low"
  },
  "cudagraph_base_bytes": {
   "value": 268435456,
   "unit": "bytes",
   "rationale": "Fixed cost of CUDA graph capture pools in vLLM when enforce_eager=False.",
   "source_url": "https://docs.vllm.ai/en/latest/configuration/optimization.html",
   "confidence": "low"
  },
  "cudagraph_bytes_per_captured_size": {
   "value": 8388608,
   "unit": "bytes",
   "rationale": "Per captured batch size, vLLM holds graph node structures and static input/output buffers. vLLM's default capture list has ~35 sizes and total graph memory is typically 1-3 GiB.",
   "source_url": "https://github.com/vllm-project/vllm/blob/main/vllm/config/compilation.py",
   "confidence": "low"
  },
  "prefill_activation_multiplier": {
   "value": 4,
   "unit": "count",
   "rationale": "Number of live hidden-size-shaped activation buffers during a prefill chunk (residual stream, qkv projection output, attention output, plus one transient). Flash-attention avoids materialising the S x S score matrix, so the quadratic term is excluded.",
   "source_url": "https://arxiv.org/abs/2205.14135",
   "confidence": "medium"
  },
  "allocator_fragmentation_fraction": {
   "value": 0.02,
   "unit": "fraction",
   "rationale": "PyTorch caching allocator holds reserved-but-unallocated blocks. vLLM's profiling run measures peak reserved, not peak allocated, so a small slack remains.",
   "source_url": "https://pytorch.org/docs/stable/notes/cuda.html#memory-management",
   "confidence": "low"
  },
  "mbu_decode": {
   "value": 0.65,
   "unit": "fraction",
   "rationale": "Model Bandwidth Utilisation achieved by a well-tuned decode kernel on a modern engine. Databricks measured 0.55-0.72 across model sizes on A100/H100.",
   "source_url": "https://www.databricks.com/blog/llm-inference-performance-engineering-best-practices",
   "confidence": "medium"
  },
  "mfu_prefill": {
   "value": 0.45,
   "unit": "fraction",
   "rationale": "Model FLOPs Utilisation for compute-bound prefill. PaLM reported 0.46 MFU for training; large-batch prefill lands in a similar band, lower for small hidden sizes.",
   "source_url": "https://arxiv.org/abs/2204.02311",
   "confidence": "medium"
  },
  "quant_group_size": {
   "value": 128,
   "unit": "count",
   "rationale": "Default group size for GPTQ/AWQ int4 packing. Each group carries a scale (and a zero point for asymmetric schemes).",
   "source_url": "https://arxiv.org/abs/2306.00978",
   "confidence": "high"
  },
  "interconnect_efficiency": {
   "value": 0.7,
   "unit": "fraction",
   "rationale": "Fraction of peak NVLink/PCIe bandwidth achieved by NCCL all-reduce at the message sizes typical of TP (a few MiB).",
   "source_url": "https://github.com/NVIDIA/nccl-tests",
   "confidence": "low"
  }
 },
 "quant": {
  "_note": "Effective bits-per-weight. GGUF k-quant values are MEASURED over a whole LLaMA-7B file (all tensors, mixed precision inside the scheme), not the nominal bit width of the block format. Non-GGUF schemes carry a tensorPolicy instead, because their overhead is computed analytically from group size.",
  "gguf": {
   "_source_url": "https://github.com/ggml-org/llama.cpp/pull/1684",
   "bpw": {
    "Q2_K": 3.35,
    "Q3_K_S": 3.5,
    "Q3_K_M": 3.89,
    "Q3_K_L": 4.27,
    "Q4_0": 4.55,
    "Q4_1": 5,
    "Q4_K_S": 4.58,
    "Q4_K_M": 4.85,
    "Q5_0": 5.54,
    "Q5_1": 6,
    "Q5_K_S": 5.52,
    "Q5_K_M": 5.69,
    "Q6_K": 6.59,
    "Q8_0": 8.5,
    "F16": 16
   }
  },
  "schemes": {
   "fp32": {
    "bits": 32,
    "kind": "dense",
    "tensorPolicy": {}
   },
   "fp16": {
    "bits": 16,
    "kind": "dense",
    "tensorPolicy": {}
   },
   "bf16": {
    "bits": 16,
    "kind": "dense",
    "tensorPolicy": {}
   },
   "fp8": {
    "bits": 8,
    "kind": "dense",
    "tensorPolicy": {
     "embedding": 16,
     "lm_head": 16,
     "norm": 16
    },
    "scaleBitsPerTensor": 32,
    "source_url": "https://docs.vllm.ai/en/latest/features/quantization/fp8.html"
   },
   "int8": {
    "bits": 8,
    "kind": "grouped",
    "groupSize": 128,
    "scaleBits": 16,
    "zeroBits": 0,
    "tensorPolicy": {
     "embedding": 16,
     "lm_head": 16,
     "norm": 16
    },
    "source_url": "https://arxiv.org/abs/2211.10438"
   },
   "awq-int4": {
    "bits": 4,
    "kind": "grouped",
    "groupSize": 128,
    "scaleBits": 16,
    "zeroBits": 4,
    "tensorPolicy": {
     "embedding": 16,
     "lm_head": 16,
     "norm": 16
    },
    "source_url": "https://arxiv.org/abs/2306.00978"
   },
   "gptq-int4": {
    "bits": 4,
    "kind": "grouped",
    "groupSize": 128,
    "scaleBits": 16,
    "zeroBits": 4,
    "tensorPolicy": {
     "embedding": 16,
     "lm_head": 16,
     "norm": 16
    },
    "source_url": "https://arxiv.org/abs/2210.17323"
   },
   "mxfp4": {
    "bits": 4,
    "kind": "grouped",
    "groupSize": 32,
    "scaleBits": 8,
    "zeroBits": 0,
    "tensorPolicy": {
     "embedding": 16,
     "lm_head": 16,
     "norm": 16
    },
    "source_url": "https://www.opencompute.org/documents/ocp-microscaling-formats-mx-v1-0-spec-final-pdf"
   }
  },
  "kvDtypeBits": {
   "_note": "fp8 KV in vLLM stores E4M3 elements plus a per-tensor scale; the per-token cost is the element width.",
   "fp32": 32,
   "fp16": 16,
   "bf16": 16,
   "fp8": 8,
   "fp8_e5m2": 8,
   "fp8_e4m3": 8,
   "int8": 8
  }
 },
 "archDefaults": {
  "gemma3_text": {
   "source_url": "https://github.com/huggingface/transformers/blob/main/src/transformers/models/gemma3/configuration_gemma3.py",
   "fields": {
    "vocab_size": 262208,
    "max_position_embeddings": 131072,
    "tie_word_embeddings": true,
    "sliding_window_pattern": 6,
    "rope_theta": 1000000
   }
  },
  "gemma3": {
   "source_url": "https://github.com/huggingface/transformers/blob/main/src/transformers/models/gemma3/configuration_gemma3.py",
   "fields": {
    "vocab_size": 262208,
    "max_position_embeddings": 131072,
    "tie_word_embeddings": true,
    "sliding_window_pattern": 6
   }
  },
  "gemma2": {
   "source_url": "https://github.com/huggingface/transformers/blob/main/src/transformers/models/gemma2/configuration_gemma2.py",
   "fields": {
    "tie_word_embeddings": true,
    "sliding_window_pattern": 2
   }
  },
  "gemma": {
   "source_url": "https://github.com/huggingface/transformers/blob/main/src/transformers/models/gemma/configuration_gemma.py",
   "fields": {
    "tie_word_embeddings": true
   }
  }
 },
 "validation": [],
 "models": {
  "Qwen/Qwen2.5-72B-Instruct": {
   "id": "Qwen/Qwen2.5-72B-Instruct",
   "fetchedFrom": "Qwen/Qwen2.5-72B-Instruct",
   "gated": false,
   "source_url": "https://huggingface.co/Qwen/Qwen2.5-72B-Instruct/resolve/main/config.json",
   "measuredWeightBytes": 145412519312,
   "measuredWeightSource": "https://huggingface.co/api/models/Qwen/Qwen2.5-72B-Instruct/tree/main (37 weight files)",
   "indexTotalSize": 145412407296,
   "config": {
    "architectures": [
     "Qwen2ForCausalLM"
    ],
    "attention_dropout": 0,
    "bos_token_id": 151643,
    "eos_token_id": 151645,
    "hidden_act": "silu",
    "hidden_size": 8192,
    "initializer_range": 0.02,
    "intermediate_size": 29568,
    "max_position_embeddings": 32768,
    "max_window_layers": 70,
    "model_type": "qwen2",
    "num_attention_heads": 64,
    "num_hidden_layers": 80,
    "num_key_value_heads": 8,
    "rms_norm_eps": 0.000001,
    "rope_theta": 1000000,
    "sliding_window": 131072,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.43.1",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 152064
   }
  },
  "Qwen/Qwen2.5-7B-Instruct": {
   "id": "Qwen/Qwen2.5-7B-Instruct",
   "fetchedFrom": "Qwen/Qwen2.5-7B-Instruct",
   "gated": false,
   "source_url": "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct/resolve/main/config.json",
   "measuredWeightBytes": 15231271888,
   "measuredWeightSource": "https://huggingface.co/api/models/Qwen/Qwen2.5-7B-Instruct/tree/main (4 weight files)",
   "indexTotalSize": 15231233024,
   "config": {
    "architectures": [
     "Qwen2ForCausalLM"
    ],
    "attention_dropout": 0,
    "bos_token_id": 151643,
    "eos_token_id": 151645,
    "hidden_act": "silu",
    "hidden_size": 3584,
    "initializer_range": 0.02,
    "intermediate_size": 18944,
    "max_position_embeddings": 32768,
    "max_window_layers": 28,
    "model_type": "qwen2",
    "num_attention_heads": 28,
    "num_hidden_layers": 28,
    "num_key_value_heads": 4,
    "rms_norm_eps": 0.000001,
    "rope_theta": 1000000,
    "sliding_window": 131072,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.43.1",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 152064
   }
  },
  "Qwen/Qwen3-235B-A22B": {
   "id": "Qwen/Qwen3-235B-A22B",
   "fetchedFrom": "Qwen/Qwen3-235B-A22B",
   "gated": false,
   "source_url": "https://huggingface.co/Qwen/Qwen3-235B-A22B/resolve/main/config.json",
   "measuredWeightBytes": 470191875096,
   "measuredWeightSource": "https://huggingface.co/api/models/Qwen/Qwen3-235B-A22B/tree/main (118 weight files)",
   "indexTotalSize": 470187269120,
   "config": {
    "architectures": [
     "Qwen3MoeForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 151643,
    "decoder_sparse_step": 1,
    "eos_token_id": 151645,
    "head_dim": 128,
    "hidden_act": "silu",
    "hidden_size": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 12288,
    "max_position_embeddings": 40960,
    "max_window_layers": 94,
    "mlp_only_layers": [],
    "model_type": "qwen3_moe",
    "moe_intermediate_size": 1536,
    "norm_topk_prob": true,
    "num_attention_heads": 64,
    "num_experts": 128,
    "num_experts_per_tok": 8,
    "num_hidden_layers": 94,
    "num_key_value_heads": 4,
    "output_router_logits": false,
    "rms_norm_eps": 0.000001,
    "rope_scaling": null,
    "rope_theta": 1000000,
    "router_aux_loss_coef": 0.001,
    "sliding_window": null,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.51.0",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 151936
   }
  },
  "Qwen/Qwen3-30B-A3B": {
   "id": "Qwen/Qwen3-30B-A3B",
   "fetchedFrom": "Qwen/Qwen3-30B-A3B",
   "gated": false,
   "source_url": "https://huggingface.co/Qwen/Qwen3-30B-A3B/resolve/main/config.json",
   "measuredWeightBytes": 61066575648,
   "measuredWeightSource": "https://huggingface.co/api/models/Qwen/Qwen3-30B-A3B/tree/main (16 weight files)",
   "indexTotalSize": 61064245248,
   "config": {
    "architectures": [
     "Qwen3MoeForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 151643,
    "decoder_sparse_step": 1,
    "eos_token_id": 151645,
    "head_dim": 128,
    "hidden_act": "silu",
    "hidden_size": 2048,
    "initializer_range": 0.02,
    "intermediate_size": 6144,
    "max_position_embeddings": 40960,
    "max_window_layers": 48,
    "mlp_only_layers": [],
    "model_type": "qwen3_moe",
    "moe_intermediate_size": 768,
    "norm_topk_prob": true,
    "num_attention_heads": 32,
    "num_experts": 128,
    "num_experts_per_tok": 8,
    "num_hidden_layers": 48,
    "num_key_value_heads": 4,
    "output_router_logits": false,
    "rms_norm_eps": 0.000001,
    "rope_scaling": null,
    "rope_theta": 1000000,
    "router_aux_loss_coef": 0.001,
    "sliding_window": null,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.51.0",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 151936
   }
  },
  "Qwen/Qwen3-32B": {
   "id": "Qwen/Qwen3-32B",
   "fetchedFrom": "Qwen/Qwen3-32B",
   "gated": false,
   "source_url": "https://huggingface.co/Qwen/Qwen3-32B/resolve/main/config.json",
   "measuredWeightBytes": 65524328560,
   "measuredWeightSource": "https://huggingface.co/api/models/Qwen/Qwen3-32B/tree/main (17 weight files)",
   "indexTotalSize": 65524246528,
   "config": {
    "architectures": [
     "Qwen3ForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 151643,
    "eos_token_id": 151645,
    "head_dim": 128,
    "hidden_act": "silu",
    "hidden_size": 5120,
    "initializer_range": 0.02,
    "intermediate_size": 25600,
    "max_position_embeddings": 40960,
    "max_window_layers": 64,
    "model_type": "qwen3",
    "num_attention_heads": 64,
    "num_hidden_layers": 64,
    "num_key_value_heads": 8,
    "rms_norm_eps": 0.000001,
    "rope_scaling": null,
    "rope_theta": 1000000,
    "sliding_window": null,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.51.0",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 151936
   }
  },
  "Qwen/Qwen3-8B": {
   "id": "Qwen/Qwen3-8B",
   "fetchedFrom": "Qwen/Qwen3-8B",
   "gated": false,
   "source_url": "https://huggingface.co/Qwen/Qwen3-8B/resolve/main/config.json",
   "measuredWeightBytes": 16381516776,
   "measuredWeightSource": "https://huggingface.co/api/models/Qwen/Qwen3-8B/tree/main (5 weight files)",
   "indexTotalSize": 16381470720,
   "config": {
    "architectures": [
     "Qwen3ForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 151643,
    "eos_token_id": 151645,
    "head_dim": 128,
    "hidden_act": "silu",
    "hidden_size": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 12288,
    "max_position_embeddings": 40960,
    "max_window_layers": 36,
    "model_type": "qwen3",
    "num_attention_heads": 32,
    "num_hidden_layers": 36,
    "num_key_value_heads": 8,
    "rms_norm_eps": 0.000001,
    "rope_scaling": null,
    "rope_theta": 1000000,
    "sliding_window": null,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.51.0",
    "use_cache": true,
    "use_sliding_window": false,
    "vocab_size": 151936
   }
  },
  "deepseek-ai/DeepSeek-R1": {
   "id": "deepseek-ai/DeepSeek-R1",
   "fetchedFrom": "deepseek-ai/DeepSeek-R1",
   "gated": false,
   "source_url": "https://huggingface.co/deepseek-ai/DeepSeek-R1/resolve/main/config.json",
   "measuredWeightBytes": 688586727753,
   "measuredWeightSource": "https://huggingface.co/api/models/deepseek-ai/DeepSeek-R1/tree/main (163 weight files)",
   "indexTotalSize": 1369062772000,
   "config": {
    "architectures": [
     "DeepseekV3ForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "auto_map": {
     "AutoConfig": "configuration_deepseek.DeepseekV3Config",
     "AutoModel": "modeling_deepseek.DeepseekV3Model",
     "AutoModelForCausalLM": "modeling_deepseek.DeepseekV3ForCausalLM"
    },
    "bos_token_id": 0,
    "eos_token_id": 1,
    "ep_size": 1,
    "first_k_dense_replace": 3,
    "hidden_act": "silu",
    "hidden_size": 7168,
    "initializer_range": 0.02,
    "intermediate_size": 18432,
    "kv_lora_rank": 512,
    "max_position_embeddings": 163840,
    "model_type": "deepseek_v3",
    "moe_intermediate_size": 2048,
    "moe_layer_freq": 1,
    "n_group": 8,
    "n_routed_experts": 256,
    "n_shared_experts": 1,
    "norm_topk_prob": true,
    "num_attention_heads": 128,
    "num_experts_per_tok": 8,
    "num_hidden_layers": 61,
    "num_key_value_heads": 128,
    "num_nextn_predict_layers": 1,
    "q_lora_rank": 1536,
    "qk_nope_head_dim": 128,
    "qk_rope_head_dim": 64,
    "quantization_config": {
     "activation_scheme": "dynamic",
     "fmt": "e4m3",
     "quant_method": "fp8",
     "weight_block_size": [
      128,
      128
     ]
    },
    "rms_norm_eps": 0.000001,
    "rope_scaling": {
     "beta_fast": 32,
     "beta_slow": 1,
     "factor": 40,
     "mscale": 1,
     "mscale_all_dim": 1,
     "original_max_position_embeddings": 4096,
     "type": "yarn"
    },
    "rope_theta": 10000,
    "routed_scaling_factor": 2.5,
    "scoring_func": "sigmoid",
    "tie_word_embeddings": false,
    "topk_group": 4,
    "topk_method": "noaux_tc",
    "torch_dtype": "bfloat16",
    "transformers_version": "4.46.3",
    "use_cache": true,
    "v_head_dim": 128,
    "vocab_size": 129280
   }
  },
  "deepseek-ai/DeepSeek-V2-Lite": {
   "id": "deepseek-ai/DeepSeek-V2-Lite",
   "fetchedFrom": "deepseek-ai/DeepSeek-V2-Lite",
   "gated": false,
   "source_url": "https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite/resolve/main/config.json",
   "measuredWeightBytes": 31413626576,
   "measuredWeightSource": "https://huggingface.co/api/models/deepseek-ai/DeepSeek-V2-Lite/tree/main (4 weight files)",
   "indexTotalSize": 31412968448,
   "config": {
    "architectures": [
     "DeepseekV2ForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "auto_map": {
     "AutoConfig": "configuration_deepseek.DeepseekV2Config",
     "AutoModel": "modeling_deepseek.DeepseekV2Model",
     "AutoModelForCausalLM": "modeling_deepseek.DeepseekV2ForCausalLM"
    },
    "aux_loss_alpha": 0.001,
    "bos_token_id": 100000,
    "eos_token_id": 100001,
    "first_k_dense_replace": 1,
    "hidden_act": "silu",
    "hidden_size": 2048,
    "initializer_range": 0.02,
    "intermediate_size": 10944,
    "kv_lora_rank": 512,
    "max_position_embeddings": 163840,
    "model_type": "deepseek_v2",
    "moe_intermediate_size": 1408,
    "moe_layer_freq": 1,
    "n_group": 1,
    "n_routed_experts": 64,
    "n_shared_experts": 2,
    "norm_topk_prob": false,
    "num_attention_heads": 16,
    "num_experts_per_tok": 6,
    "num_hidden_layers": 27,
    "num_key_value_heads": 16,
    "pretraining_tp": 1,
    "q_lora_rank": null,
    "qk_nope_head_dim": 128,
    "qk_rope_head_dim": 64,
    "rms_norm_eps": 0.000001,
    "rope_scaling": {
     "beta_fast": 32,
     "beta_slow": 1,
     "factor": 40,
     "mscale": 0.707,
     "mscale_all_dim": 0.707,
     "original_max_position_embeddings": 4096,
     "type": "yarn"
    },
    "rope_theta": 10000,
    "routed_scaling_factor": 1,
    "scoring_func": "softmax",
    "seq_aux": true,
    "tie_word_embeddings": false,
    "topk_group": 1,
    "topk_method": "greedy",
    "torch_dtype": "bfloat16",
    "transformers_version": "4.33.1",
    "use_cache": true,
    "v_head_dim": 128,
    "vocab_size": 102400
   }
  },
  "deepseek-ai/DeepSeek-V3": {
   "id": "deepseek-ai/DeepSeek-V3",
   "fetchedFrom": "deepseek-ai/DeepSeek-V3",
   "gated": false,
   "source_url": "https://huggingface.co/deepseek-ai/DeepSeek-V3/resolve/main/config.json",
   "measuredWeightBytes": 688586727753,
   "measuredWeightSource": "https://huggingface.co/api/models/deepseek-ai/DeepSeek-V3/tree/main (163 weight files)",
   "indexTotalSize": 1369062772000,
   "config": {
    "architectures": [
     "DeepseekV3ForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "auto_map": {
     "AutoConfig": "configuration_deepseek.DeepseekV3Config",
     "AutoModel": "modeling_deepseek.DeepseekV3Model",
     "AutoModelForCausalLM": "modeling_deepseek.DeepseekV3ForCausalLM"
    },
    "bos_token_id": 0,
    "eos_token_id": 1,
    "ep_size": 1,
    "first_k_dense_replace": 3,
    "hidden_act": "silu",
    "hidden_size": 7168,
    "initializer_range": 0.02,
    "intermediate_size": 18432,
    "kv_lora_rank": 512,
    "max_position_embeddings": 163840,
    "model_type": "deepseek_v3",
    "moe_intermediate_size": 2048,
    "moe_layer_freq": 1,
    "n_group": 8,
    "n_routed_experts": 256,
    "n_shared_experts": 1,
    "norm_topk_prob": true,
    "num_attention_heads": 128,
    "num_experts_per_tok": 8,
    "num_hidden_layers": 61,
    "num_key_value_heads": 128,
    "num_nextn_predict_layers": 1,
    "q_lora_rank": 1536,
    "qk_nope_head_dim": 128,
    "qk_rope_head_dim": 64,
    "quantization_config": {
     "activation_scheme": "dynamic",
     "fmt": "e4m3",
     "quant_method": "fp8",
     "weight_block_size": [
      128,
      128
     ]
    },
    "rms_norm_eps": 0.000001,
    "rope_scaling": {
     "beta_fast": 32,
     "beta_slow": 1,
     "factor": 40,
     "mscale": 1,
     "mscale_all_dim": 1,
     "original_max_position_embeddings": 4096,
     "type": "yarn"
    },
    "rope_theta": 10000,
    "routed_scaling_factor": 2.5,
    "scoring_func": "sigmoid",
    "tie_word_embeddings": false,
    "topk_group": 4,
    "topk_method": "noaux_tc",
    "torch_dtype": "bfloat16",
    "transformers_version": "4.33.1",
    "use_cache": true,
    "v_head_dim": 128,
    "vocab_size": 129280
   }
  },
  "google/gemma-2-9b-it": {
   "id": "google/gemma-2-9b-it",
   "fetchedFrom": "google/gemma-2-9b-it",
   "gated": false,
   "source_url": "https://huggingface.co/google/gemma-2-9b-it/resolve/main/config.json",
   "measuredWeightBytes": 18483466448,
   "measuredWeightSource": "https://huggingface.co/api/models/google/gemma-2-9b-it/tree/main (4 weight files)",
   "indexTotalSize": 18483411968,
   "config": {
    "architectures": [
     "Gemma2ForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "attn_logit_softcapping": 50,
    "bos_token_id": 2,
    "cache_implementation": "hybrid",
    "eos_token_id": 1,
    "final_logit_softcapping": 30,
    "head_dim": 256,
    "hidden_act": "gelu_pytorch_tanh",
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 3584,
    "initializer_range": 0.02,
    "intermediate_size": 14336,
    "max_position_embeddings": 8192,
    "model_type": "gemma2",
    "num_attention_heads": 16,
    "num_hidden_layers": 42,
    "num_key_value_heads": 8,
    "pad_token_id": 0,
    "query_pre_attn_scalar": 256,
    "rms_norm_eps": 0.000001,
    "rope_theta": 10000,
    "sliding_window": 4096,
    "sliding_window_size": 4096,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.42.0.dev0",
    "use_cache": true,
    "vocab_size": 256000
   }
  },
  "google/gemma-3-27b-it": {
   "id": "google/gemma-3-27b-it",
   "fetchedFrom": "google/gemma-3-27b-it",
   "gated": false,
   "source_url": "https://huggingface.co/google/gemma-3-27b-it/resolve/main/config.json",
   "measuredWeightBytes": 54864980440,
   "measuredWeightSource": "https://huggingface.co/api/models/google/gemma-3-27b-it/tree/main (12 weight files)",
   "indexTotalSize": 54864813280,
   "config": {
    "architectures": [
     "Gemma3ForConditionalGeneration"
    ],
    "boi_token_index": 255999,
    "eoi_token_index": 256000,
    "eos_token_id": [
     1,
     106
    ],
    "image_token_index": 262144,
    "initializer_range": 0.02,
    "mm_tokens_per_image": 256,
    "model_type": "gemma3",
    "text_config": {
     "head_dim": 128,
     "hidden_size": 5376,
     "intermediate_size": 21504,
     "model_type": "gemma3_text",
     "num_attention_heads": 32,
     "num_hidden_layers": 62,
     "num_key_value_heads": 16,
     "query_pre_attn_scalar": 168,
     "rope_scaling": {
      "factor": 8,
      "rope_type": "linear"
     },
     "sliding_window": 1024
    },
    "torch_dtype": "bfloat16",
    "transformers_version": "4.50.0.dev0",
    "vision_config": {
     "hidden_size": 1152,
     "image_size": 896,
     "intermediate_size": 4304,
     "model_type": "siglip_vision_model",
     "num_attention_heads": 16,
     "num_hidden_layers": 27,
     "patch_size": 14,
     "vision_use_head": false
    }
   }
  },
  "meta-llama/Llama-3.1-405B-Instruct": {
   "id": "meta-llama/Llama-3.1-405B-Instruct",
   "fetchedFrom": "meta-llama/Llama-3.1-405B-Instruct",
   "gated": false,
   "source_url": "https://huggingface.co/meta-llama/Llama-3.1-405B-Instruct/resolve/main/config.json",
   "measuredWeightBytes": 811706916800,
   "measuredWeightSource": "https://huggingface.co/api/models/meta-llama/Llama-3.1-405B-Instruct/tree/main (191 weight files)",
   "indexTotalSize": 811706777600,
   "config": {
    "_name_or_path": ".",
    "architectures": [
     "LlamaForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 128000,
    "eos_token_id": [
     128001,
     128008,
     128009
    ],
    "hidden_act": "silu",
    "hidden_size": 16384,
    "initializer_range": 0.02,
    "intermediate_size": 53248,
    "max_position_embeddings": 131072,
    "mlp_bias": false,
    "model_type": "llama",
    "num_attention_heads": 128,
    "num_hidden_layers": 126,
    "num_key_value_heads": 8,
    "pretraining_tp": 1,
    "rms_norm_eps": 0.00001,
    "rope_scaling": {
     "factor": 8,
     "high_freq_factor": 4,
     "low_freq_factor": 1,
     "original_max_position_embeddings": 8192,
     "rope_type": "llama3"
    },
    "rope_theta": 500000,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.43.3",
    "use_cache": true,
    "vocab_size": 128256
   }
  },
  "meta-llama/Llama-3.1-70B-Instruct": {
   "id": "meta-llama/Llama-3.1-70B-Instruct",
   "fetchedFrom": "meta-llama/Llama-3.1-70B-Instruct",
   "gated": false,
   "source_url": "https://huggingface.co/meta-llama/Llama-3.1-70B-Instruct/resolve/main/config.json",
   "measuredWeightBytes": 141107497872,
   "measuredWeightSource": "https://huggingface.co/api/models/meta-llama/Llama-3.1-70B-Instruct/tree/main (30 weight files)",
   "indexTotalSize": 141107412992,
   "config": {
    "architectures": [
     "LlamaForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 128000,
    "eos_token_id": [
     128001,
     128008,
     128009
    ],
    "hidden_act": "silu",
    "hidden_size": 8192,
    "initializer_range": 0.02,
    "intermediate_size": 28672,
    "max_position_embeddings": 131072,
    "mlp_bias": false,
    "model_type": "llama",
    "num_attention_heads": 64,
    "num_hidden_layers": 80,
    "num_key_value_heads": 8,
    "pretraining_tp": 1,
    "rms_norm_eps": 0.00001,
    "rope_scaling": {
     "factor": 8,
     "low_freq_factor": 1,
     "high_freq_factor": 4,
     "original_max_position_embeddings": 8192,
     "rope_type": "llama3"
    },
    "rope_theta": 500000,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.42.3",
    "use_cache": true,
    "vocab_size": 128256
   }
  },
  "meta-llama/Llama-3.1-8B-Instruct": {
   "id": "meta-llama/Llama-3.1-8B-Instruct",
   "fetchedFrom": "meta-llama/Llama-3.1-8B-Instruct",
   "gated": false,
   "source_url": "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct/resolve/main/config.json",
   "measuredWeightBytes": 16060556376,
   "measuredWeightSource": "https://huggingface.co/api/models/meta-llama/Llama-3.1-8B-Instruct/tree/main (4 weight files)",
   "indexTotalSize": 16060522496,
   "config": {
    "architectures": [
     "LlamaForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 128000,
    "eos_token_id": [
     128001,
     128008,
     128009
    ],
    "hidden_act": "silu",
    "hidden_size": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 14336,
    "max_position_embeddings": 131072,
    "mlp_bias": false,
    "model_type": "llama",
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "num_key_value_heads": 8,
    "pretraining_tp": 1,
    "rms_norm_eps": 0.00001,
    "rope_scaling": {
     "factor": 8,
     "low_freq_factor": 1,
     "high_freq_factor": 4,
     "original_max_position_embeddings": 8192,
     "rope_type": "llama3"
    },
    "rope_theta": 500000,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.42.3",
    "use_cache": true,
    "vocab_size": 128256
   }
  },
  "meta-llama/Llama-3.2-3B-Instruct": {
   "id": "meta-llama/Llama-3.2-3B-Instruct",
   "fetchedFrom": "meta-llama/Llama-3.2-3B-Instruct",
   "gated": false,
   "source_url": "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct/resolve/main/config.json",
   "measuredWeightBytes": 6425529048,
   "measuredWeightSource": "https://huggingface.co/api/models/meta-llama/Llama-3.2-3B-Instruct/tree/main (2 weight files)",
   "indexTotalSize": 6425499648,
   "config": {
    "architectures": [
     "LlamaForCausalLM"
    ],
    "attention_bias": false,
    "attention_dropout": 0,
    "bos_token_id": 128000,
    "eos_token_id": [
     128001,
     128008,
     128009
    ],
    "head_dim": 128,
    "hidden_act": "silu",
    "hidden_size": 3072,
    "initializer_range": 0.02,
    "intermediate_size": 8192,
    "max_position_embeddings": 131072,
    "mlp_bias": false,
    "model_type": "llama",
    "num_attention_heads": 24,
    "num_hidden_layers": 28,
    "num_key_value_heads": 8,
    "pretraining_tp": 1,
    "rms_norm_eps": 0.00001,
    "rope_scaling": {
     "factor": 32,
     "high_freq_factor": 4,
     "low_freq_factor": 1,
     "original_max_position_embeddings": 8192,
     "rope_type": "llama3"
    },
    "rope_theta": 500000,
    "tie_word_embeddings": true,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.45.0.dev0",
    "use_cache": true,
    "vocab_size": 128256
   }
  },
  "microsoft/Phi-3.5-mini-instruct": {
   "id": "microsoft/Phi-3.5-mini-instruct",
   "fetchedFrom": "microsoft/Phi-3.5-mini-instruct",
   "gated": false,
   "source_url": "https://huggingface.co/microsoft/Phi-3.5-mini-instruct/resolve/main/config.json",
   "measuredWeightBytes": 7642181880,
   "measuredWeightSource": "https://huggingface.co/api/models/microsoft/Phi-3.5-mini-instruct/tree/main (2 weight files)",
   "indexTotalSize": 7642159104,
   "config": {
    "_name_or_path": "Phi-3.5-mini-instruct",
    "architectures": [
     "Phi3ForCausalLM"
    ],
    "attention_dropout": 0,
    "auto_map": {
     "AutoConfig": "configuration_phi3.Phi3Config",
     "AutoModelForCausalLM": "modeling_phi3.Phi3ForCausalLM"
    },
    "bos_token_id": 1,
    "embd_pdrop": 0,
    "eos_token_id": 32000,
    "hidden_act": "silu",
    "hidden_size": 3072,
    "initializer_range": 0.02,
    "intermediate_size": 8192,
    "max_position_embeddings": 131072,
    "model_type": "phi3",
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "num_key_value_heads": 32,
    "original_max_position_embeddings": 4096,
    "pad_token_id": 32000,
    "resid_pdrop": 0,
    "rms_norm_eps": 0.00001,
    "rope_scaling": {
     "long_factor": [
      1.0800000429153442,
      1.1100000143051147,
      1.1399999856948853,
      1.340000033378601,
      1.5899999141693115,
      1.600000023841858,
      1.6200000047683716,
      2.620000123977661,
      3.2300000190734863,
      3.2300000190734863,
      4.789999961853027,
      7.400000095367432,
      7.700000286102295,
      9.09000015258789,
      12.199999809265137,
      17.670000076293945,
      24.46000099182129,
      28.57000160217285,
      30.420001983642578,
      30.840002059936523,
      32.590003967285156,
      32.93000411987305,
      42.320003509521484,
      44.96000289916992,
      50.340003967285156,
      50.45000457763672,
      57.55000305175781,
      57.93000411987305,
      58.21000289916992,
      60.1400032043457,
      62.61000442504883,
      62.62000274658203,
      62.71000289916992,
      63.1400032043457,
      63.1400032043457,
      63.77000427246094,
      63.93000411987305,
      63.96000289916992,
      63.970001220703125,
      64.02999877929688,
      64.06999969482422,
      64.08000183105469,
      64.12000274658203,
      64.41000366210938,
      64.4800033569336,
      64.51000213623047,
      64.52999877929688,
      64.83999633789062
     ],
     "short_factor": [
      1,
      1.0199999809265137,
      1.0299999713897705,
      1.0299999713897705,
      1.0499999523162842,
      1.0499999523162842,
      1.0499999523162842,
      1.0499999523162842,
      1.0499999523162842,
      1.0699999332427979,
      1.0999999046325684,
      1.1099998950958252,
      1.1599998474121094,
      1.1599998474121094,
      1.1699998378753662,
      1.2899998426437378,
      1.339999794960022,
      1.679999828338623,
      1.7899998426437378,
      1.8199998140335083,
      1.8499997854232788,
      1.8799997568130493,
      1.9099997282028198,
      1.9399996995925903,
      1.9899996519088745,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0199997425079346,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0299997329711914,
      2.0799996852874756,
      2.0899996757507324,
      2.189999580383301,
      2.2199995517730713,
      2.5899994373321533,
      2.729999542236328,
      2.749999523162842,
      2.8399994373321533
     ],
     "type": "longrope"
    },
    "rope_theta": 10000,
    "sliding_window": 262144,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.43.3",
    "use_cache": true,
    "attention_bias": false,
    "vocab_size": 32064
   }
  },
  "mistralai/Mistral-7B-Instruct-v0.3": {
   "id": "mistralai/Mistral-7B-Instruct-v0.3",
   "fetchedFrom": "mistralai/Mistral-7B-Instruct-v0.3",
   "gated": false,
   "source_url": "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3/resolve/main/config.json",
   "measuredWeightBytes": 14496080928,
   "measuredWeightSource": "https://huggingface.co/api/models/mistralai/Mistral-7B-Instruct-v0.3/tree/main (3 weight files)",
   "indexTotalSize": 14496047104,
   "config": {
    "architectures": [
     "MistralForCausalLM"
    ],
    "attention_dropout": 0,
    "bos_token_id": 1,
    "eos_token_id": 2,
    "hidden_act": "silu",
    "hidden_size": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 14336,
    "max_position_embeddings": 32768,
    "model_type": "mistral",
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "num_key_value_heads": 8,
    "rms_norm_eps": 0.00001,
    "rope_theta": 1000000,
    "sliding_window": null,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.42.0.dev0",
    "use_cache": true,
    "vocab_size": 32768
   }
  },
  "mistralai/Mixtral-8x7B-Instruct-v0.1": {
   "id": "mistralai/Mixtral-8x7B-Instruct-v0.1",
   "fetchedFrom": "mistralai/Mixtral-8x7B-Instruct-v0.1",
   "gated": false,
   "source_url": "https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1/resolve/main/config.json",
   "measuredWeightBytes": 93405713504,
   "measuredWeightSource": "https://huggingface.co/api/models/mistralai/Mixtral-8x7B-Instruct-v0.1/tree/main (19 weight files)",
   "indexTotalSize": 93405585408,
   "config": {
    "architectures": [
     "MixtralForCausalLM"
    ],
    "attention_dropout": 0,
    "bos_token_id": 1,
    "eos_token_id": 2,
    "hidden_act": "silu",
    "hidden_size": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 14336,
    "max_position_embeddings": 32768,
    "model_type": "mixtral",
    "num_attention_heads": 32,
    "num_experts_per_tok": 2,
    "num_hidden_layers": 32,
    "num_key_value_heads": 8,
    "num_local_experts": 8,
    "output_router_logits": false,
    "rms_norm_eps": 0.00001,
    "rope_theta": 1000000,
    "router_aux_loss_coef": 0.02,
    "sliding_window": null,
    "tie_word_embeddings": false,
    "torch_dtype": "bfloat16",
    "transformers_version": "4.36.0.dev0",
    "use_cache": true,
    "vocab_size": 32000
   }
  },
  "openai/gpt-oss-120b": {
   "id": "openai/gpt-oss-120b",
   "fetchedFrom": "openai/gpt-oss-120b",
   "gated": false,
   "source_url": "https://huggingface.co/openai/gpt-oss-120b/resolve/main/config.json",
   "measuredWeightBytes": 65248893184,
   "measuredWeightSource": "https://huggingface.co/api/models/openai/gpt-oss-120b/tree/main (15 weight files)",
   "indexTotalSize": 65248815744,
   "config": {
    "architectures": [
     "GptOssForCausalLM"
    ],
    "attention_bias": true,
    "attention_dropout": 0,
    "eos_token_id": 200002,
    "experts_per_token": 4,
    "head_dim": 64,
    "hidden_act": "silu",
    "hidden_size": 2880,
    "initial_context_length": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 2880,
    "layer_types": [
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "gpt_oss",
    "num_attention_heads": 64,
    "num_experts_per_tok": 4,
    "num_hidden_layers": 36,
    "num_key_value_heads": 8,
    "num_local_experts": 128,
    "output_router_logits": false,
    "pad_token_id": 199999,
    "quantization_config": {
     "modules_to_not_convert": [
      "model.layers.*.self_attn",
      "model.layers.*.mlp.router",
      "model.embed_tokens",
      "lm_head"
     ],
     "quant_method": "mxfp4"
    },
    "rms_norm_eps": 0.00001,
    "rope_scaling": {
     "beta_fast": 32,
     "beta_slow": 1,
     "factor": 32,
     "original_max_position_embeddings": 4096,
     "rope_type": "yarn",
     "truncate": false
    },
    "rope_theta": 150000,
    "router_aux_loss_coef": 0.9,
    "sliding_window": 128,
    "swiglu_limit": 7,
    "tie_word_embeddings": false,
    "transformers_version": "4.55.0.dev0",
    "use_cache": true,
    "vocab_size": 201088
   }
  },
  "openai/gpt-oss-20b": {
   "id": "openai/gpt-oss-20b",
   "fetchedFrom": "openai/gpt-oss-20b",
   "gated": false,
   "source_url": "https://huggingface.co/openai/gpt-oss-20b/resolve/main/config.json",
   "measuredWeightBytes": 13761316904,
   "measuredWeightSource": "https://huggingface.co/api/models/openai/gpt-oss-20b/tree/main (3 weight files)",
   "indexTotalSize": 13761264768,
   "config": {
    "architectures": [
     "GptOssForCausalLM"
    ],
    "attention_bias": true,
    "attention_dropout": 0,
    "eos_token_id": 200002,
    "experts_per_token": 4,
    "head_dim": 64,
    "hidden_act": "silu",
    "hidden_size": 2880,
    "initial_context_length": 4096,
    "initializer_range": 0.02,
    "intermediate_size": 2880,
    "layer_types": [
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention",
     "sliding_attention",
     "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "gpt_oss",
    "num_attention_heads": 64,
    "num_experts_per_tok": 4,
    "num_hidden_layers": 24,
    "num_key_value_heads": 8,
    "num_local_experts": 32,
    "output_router_logits": false,
    "pad_token_id": 199999,
    "quantization_config": {
     "modules_to_not_convert": [
      "model.layers.*.self_attn",
      "model.layers.*.mlp.router",
      "model.embed_tokens",
      "lm_head"
     ],
     "quant_method": "mxfp4"
    },
    "rms_norm_eps": 0.00001,
    "rope_scaling": {
     "beta_fast": 32,
     "beta_slow": 1,
     "factor": 32,
     "original_max_position_embeddings": 4096,
     "rope_type": "yarn",
     "truncate": false
    },
    "rope_theta": 150000,
    "router_aux_loss_coef": 0.9,
    "sliding_window": 128,
    "swiglu_limit": 7,
    "tie_word_embeddings": false,
    "transformers_version": "4.55.0.dev0",
    "use_cache": true,
    "vocab_size": 201088
   }
  }
 }
}
