// data/assumptions.json -> docs/ASSUMPTIONS.md, data/gpus.json -> docs/HARDWARE.md
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const read = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'))

const { assumptions } = read('data/assumptions.json')
const rows = Object.entries(assumptions).map(([k, a]) =>
  `### \`${k}\`

**${a.value}** ${a.unit === 'fraction' ? '(fraction)' : a.unit} · confidence: **${a.confidence}**

${a.rationale}

Source: <${a.source_url}>
`)

writeFileSync(join(ROOT, 'docs/ASSUMPTIONS.md'), `# Assumptions

Every empirical constant the model uses. Nothing is hardcoded in the math; each value below is
an entry in [\`data/assumptions.json\`](../data/assumptions.json) and is overridable at every
layer:

\`\`\`bash
llmsize plan ... --assume mbu_decode=0.72 --assume cuda_context_bytes=805306368
\`\`\`

\`\`\`ts
size({ ..., assume: { mbu_decode: 0.72 } })
\`\`\`

Confidence is honest. **low** means we could not find a primary source and the value is a
community-reported ballpark — if a prediction hinges on a low-confidence constant, that is
where to point your scepticism, and a validation log is worth more than an argument.

${rows.join('\n')}
Generated by \`pnpm gen\` from \`data/assumptions.json\`. Do not edit by hand.
`)

const { gpus } = read('data/gpus.json')
const tb = (n) => (n / 1e12).toFixed(2)
writeFileSync(join(ROOT, 'docs/HARDWARE.md'), `# Hardware

All TFLOPS are **dense** tensor-core figures. Vendor datasheets headline the 2:1
structured-sparsity number (2x dense); a unit test asserts no entry here exceeds its dense
ceiling, because quoting the sparse figure silently doubles every throughput estimate.

\`vramBytes\` is nominal capacity; the driver keeps a slice of it — see
\`driver_reserved_vram_fraction\` in [ASSUMPTIONS.md](./ASSUMPTIONS.md).

| id | VRAM | Memory | Bandwidth | bf16 | fp8 | Interconnect | Source |
| --- | --- | --- | --- | --- | --- | --- | --- |
${gpus.map((g) => `| \`${g.id}\` | ${(g.vramBytes / 2 ** 30).toFixed(0)} GiB | ${g.memoryType} | ${tb(g.memBandwidthBytesPerSec)} TB/s | ${g.tflopsDense.bf16} | ${g.tflopsDense.fp8 ?? '—'} | ${g.interconnect.kind} @ ${(g.interconnect.bidirectionalBytesPerSec / 1e9).toFixed(0)} GB/s | [datasheet](${g.source_url}) |`).join('\n')}

${gpus.filter((g) => g.notes).map((g) => `**${g.id}:** ${g.notes}`).join('\n\n')}

Adding a GPU: append to \`data/gpus.json\` with a \`source_url\`, add its known **sparse** bf16
and fp8 figures to the table in \`packages/core/test/data.test.ts\`, and run \`pnpm gen\`.

Generated by \`pnpm gen\` from \`data/gpus.json\`. Do not edit by hand.
`)

const inst = read('data/instances.json')
const gib0 = (n) => (n / 2 ** 30).toFixed(0)
writeFileSync(join(ROOT, 'docs/INSTANCES.md'), `# Rentable machines

What a sizing costs when you do not own the GPU. Every row resolves to an entry in
[HARDWARE.md](./HARDWARE.md), so the allocator that says whether a model fits is the same one
either way.

**Prices are a dated snapshot.** ${inst.pricing.basis}, \`${inst.pricing.region}\`, read on
**${inst.pricing.retrieved}** from [the AWS price list](${inst._price_source}). They move, and
nothing re-fetches them; the UI lets you substitute your own spot or savings-plan rate.

Host figures come from the [AWS accelerated computing tables](${inst._spec_source}). Network is
the **sustained** rate, not the burst ceiling a small instance holds for a few minutes.

| instance | GPUs | \$/hour | vCPU | host RAM | local NVMe | network |
| --- | --- | --- | --- | --- | --- | --- |
${inst.instances.map((i) => `| \`${i.id}\` | ${i.gpuCount}x \`${i.gpu}\` | ${inst.pricing.usdPerHour[i.id].toFixed(4)} | ${i.vcpus} | ${gib0(i.hostRamBytes)} GiB | ${(i.localDiskBytes / 1e12).toFixed(1)} TB | ${i.networkGbps} Gbps |`).join('\n')}

${inst._note}

Generated by \`pnpm gen\` from \`data/instances.json\`. Do not edit by hand.
`)

console.log('generated docs/ASSUMPTIONS.md, docs/HARDWARE.md, docs/INSTANCES.md')
