// data/*.json -> packages/core/src/generated.ts and python/llmsize/_generated.py
// Core must stay pure (no fs/fetch at runtime) and the web build must not need
// a JSON loader, so the shared data is inlined into both language ports.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const read = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'))

const bundle = {
  gpus: read('data/gpus.json').gpus,
  assumptions: read('data/assumptions.json').assumptions,
  quant: read('data/quant-bpw.json'),
  archDefaults: read('data/arch-defaults.json').byModelType,
  // Written by `pnpm validate`; absent until a real engine log has been diffed.
  validation: (() => { try { return read('data/validation-index.json') } catch { return [] } })(),
  models: Object.fromEntries(
    readdirSync(join(ROOT, 'data/models')).filter((f) => f.endsWith('.json')).map((f) => {
      const m = read(join('data/models', f))
      return [m.id, m]
    }),
  ),
}

const header = '// GENERATED by scripts/gen-data.mjs from data/. Do not edit; run `pnpm gen`.\n'
const json = JSON.stringify(bundle, null, 1)
const TQ = '"'.repeat(3)

writeFileSync(
  join(ROOT, 'packages/core/src/generated.ts'),
  header +
    'export interface DataBundle {\n' +
    '  gpus: any[]\n  assumptions: Record<string, any>\n  quant: any\n' +
    '  archDefaults: Record<string, any>\n  models: Record<string, any>\n  validation: any[]\n}\n\n' +
    'export const DATA: DataBundle = ' + json + '\n',
)
// Round-trips through json.loads so no string in the data can be corrupted by a
// naive true/false/null substitution.
writeFileSync(
  join(ROOT, 'python/llmsize/_generated.py'),
  '# ' + header.slice(3) + 'import json\n\nDATA = json.loads(r' + TQ + json + TQ + ')\n',
)
console.log(`generated: ${bundle.gpus.length} gpus, ${Object.keys(bundle.models).length} models`)
