// Diffs our predictions against real engine startup logs.
//   pnpm validate            report + write docs/VALIDATION.md + data/validation-index.json
//   pnpm validate --check    same, but exit non-zero if any case is outside tolerance (CI)
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { parse } from 'yaml'
import { size } from '../packages/core/src/plan.ts'
import { parseLog } from '../validation/parse.ts'

const ROOT = new URL('..', import.meta.url).pathname
const CASES = join(ROOT, 'validation/cases')
const GiB = 2 ** 30

// Failing one of these fails the build. Overhead is loose because it is the component
// built from assumptions rather than from architecture.
const TOLERANCE = { weights: 0.01, kv: 0.05, overhead: 0.15 }

const files = existsSync(CASES)
  ? readdirSync(CASES).filter((f) => /\.ya?ml$/.test(f) && !f.startsWith('_'))
  : []

const rows = []
let failures = 0

for (const file of files) {
  const c = parse(readFileSync(join(CASES, file), 'utf8'))
  for (const required of ['model', 'gpu', 'engine', 'engine_version', 'request', 'log']) {
    if (c?.[required] === undefined) throw new Error(`${file}: missing required key "${required}"`)
  }
  const observed = parseLog(c.engine, c.log)
  const predicted = size({ model: c.model, gpu: c.gpu, engine: c.engine, ...c.request })
  const p = predicted.plan

  const compare = [
    ['weights', p.weightBytesPerDevice, observed.weightBytes, TOLERANCE.weights],
    ['kv', p.availableKvBytes, observed.kvCacheBytes, TOLERANCE.kv],
    ['overhead', p.overhead.nonTorchBytes, observed.nonTorchBytes, TOLERANCE.overhead],
    ['activation', p.overhead.activationBytes, observed.activationBytes, TOLERANCE.overhead],
    ['maxTokens', p.maxTokens, observed.maxTokens, TOLERANCE.kv],
  ]
  const errors = {}
  for (const [name, pred, obs, tol] of compare) {
    if (obs === undefined || obs === 0) continue
    const err = (pred - obs) / obs
    errors[name] = err
    if (Math.abs(err) > tol) {
      failures++
      console.error(`FAIL ${file} ${name}: predicted ${(pred / GiB).toFixed(2)} GiB vs measured ${(obs / GiB).toFixed(2)} GiB = ${(err * 100).toFixed(1)}% (tolerance ${(tol * 100).toFixed(0)}%)`)
    }
  }
  rows.push({ model: c.model, gpu: c.gpu, engine: c.engine, engineVersion: c.engine_version, errors, caseFile: file })
  const worst = Object.entries(errors).sort((a, b) => Math.abs(b[1]) - Math.abs(a[1]))[0]
  console.log(`${failures ? ' ' : 'ok'} ${file}: ${Object.entries(errors).map(([k, v]) => `${k} ${(v * 100).toFixed(1)}%`).join(', ') || 'nothing comparable in log'}${worst ? '' : ''}`)
}

writeFileSync(join(ROOT, 'data/validation-index.json'), JSON.stringify(rows, null, 2) + '\n')

const pct = (v) => (v === undefined ? '—' : `${(v * 100).toFixed(1)}%`)
const table = rows.length
  ? ['| Model | GPU | Engine | Version | Weights | KV | Overhead | Tokens |',
     '| --- | --- | --- | --- | --- | --- | --- | --- |',
     ...rows.map((r) => `| ${r.model} | ${r.gpu} | ${r.engine} | ${r.engineVersion} | ${pct(r.errors.weights)} | ${pct(r.errors.kv)} | ${pct(r.errors.overhead)} | ${pct(r.errors.maxTokens)} |`)].join('\n')
  : '_No validation cases yet._ Every number this tool prints is **predicted**, not measured.\n\nIf you have a GPU, the fastest way to help is to paste a real engine startup log into an issue:\nhttps://github.com/varad-more/llm-calculator/issues/new?template=validation-log.yml'

writeFileSync(join(ROOT, 'docs/VALIDATION.md'), `# Validation

Signed relative error of our prediction against the engine's own startup log
(\`predicted - measured) / measured\`; negative means we under-predict.

CI tolerances: weights ±${TOLERANCE.weights * 100}%, KV ±${TOLERANCE.kv * 100}%, overhead ±${TOLERANCE.overhead * 100}%.

${table}

Generated by \`pnpm validate\` from \`validation/cases/\`. Do not edit by hand.
`)

console.log(`\n${rows.length} validation case(s), ${failures} outside tolerance`)
if (failures && process.argv.includes('--check')) process.exit(1)
